### PR TITLE
disable buy menu options based on round type

### PR DESCRIPTION
**Pull request by Shaneajm**
This will prevent issues where you can "buy" weapons that do not match the round type. The buy menu options will be disabled based on the weapon category.

image

### CODE REVIEW

**Comment by yonilerner** [comment]
This is great, I was looking for something like this. Let me play with it a bit more and tweak some things (eg. The buyable weapons should respect the `UsableWeapons` config) before merging.

Thanks

**Comment by yonilerner** [comment]
I looked into this further and unfortunately it doesn't quite work. We could do it for pistol rounds to disable everything else, but there's too much complexity in weapon allocation otherwise. For example, on half buy rounds you have to allow rifles to allow the scout and you have to allow heavies to allow shotguns. I think all in all its not really worth it to introduce this.

I will ultimately leave this up to server owners to decide if they want to set these variables despite the problems they bring.

**Comment by B3none** [comment]
I think this is a **great** idea, they should definitely be configurable values, and people may want additional settings like to disable the deagle for pistol rounds or something along those lines. Plus you will probably want to set their money for pistol rounds too.

**Comment by yonilerner** [comment]
Sorry for prematurely closing this originally, B3none is right that it can be made to work.

If we can use `mp_items_prohibited` to disallow any weapon that is not allowed for the particular round type, that could work. Theres a couple things to note here:
- The list should always include any weapon that isn't in the `UsableWeapons` config
- `Server.ExecuteCommand` cant be called from within `RetakesAllocatorCore` project. Instead, the  options are:
  - Have the `OnRoundPostStartHelper.Handle` return the command you want to execute via `out var`, and then execute it from where its called in `RetakesAllocator/RetakesAllocator.cs`
  - Pass `Server.ExecuteCommand` into `OnRoundPostStartHelper.Handle` like we do with `Func<T?, ulong> getSteamId` and other functions like that, and then use that passed in function to execute the command

We probably shouldn't remove money for pistol rounds because that would make it impossible for people to buy different pistols then. We also have to make sure not to disable any utility/armor or anything that the player needs to have (other things are preventing them from buying it).

If you wanna try to work on this, you can reach me on Discord `@yoni` if you want some help figuring out the codebase

**Comment by yonilerner** [comment]
`CounterStrikeSharp.API.Modules.Entities.Constants.ItemDefinition` contains the enum that has the values for `mp_items_prohibited`

**Comment by yonilerner** [comment]
I ended up implementing a similar idea in https://github.com/yonilerner/cs2-retakes-allocator/pull/120

**Pull request closed without merging**
