### PR TITLE
Only allocate selected weapons for the !gun command during freeze period

### PR DESCRIPTION
**Pull request by B3none**

### CODE REVIEW

**Comment by yonilerner** [comment]
Can we use the `buytime` cvar for it? I don't actually want this behavior on my server

**Comment by B3none** [comment]
> Can we use the `buytime` cvar for it? I don't actually want this behavior on my server

If we don't add this check people will be able to make a bind for `css_gun AK47` on T side to get a new weapon instead of reloading

**Comment by yonilerner** [comment]
Can we at least make it configurable in the json?

**Comment by yonilerner** [comment]
A server that wants to stop bad actors will enable this. Friend servers will find this frustrating

**Comment by B3none** [comment]
> A server that wants to stop bad actors will enable this. Friend servers will find this frustrating

You'll have to add the configs when you get chance, we should also add a config to limit the max number of awps that can be allocated too then keep track of that on the post round start allocation

**Pull request merged**
