### PR TITLE
Add AllowPreferredWeaponForOnlyVIP config for only VIPs to get preferred weapon

### PR DESCRIPTION
**Pull request by GL1TCH1337**
On my server I needed this. I don't know is it best way to do it. But it works.

### CODE REVIEW

**Comment by crashzk** [comment]
This would only be for AWP right?

If so, wouldn't it just increase the number `NumberOfExtraVipChancesForPreferredWeapon`?

- `NumberOfExtraVipChancesForPreferredWeapon`: When randomly selecting preferred weapons per team (ie. "AWP queue"), how many extra chances should VIPs get.
  - The default is 1, meaning VIPs will get 1 extra chance. For example, lets say there are 3 players on the team and this config is set to 1. Normally each person would have a 33% chance of getting the AWP, but in this case, since one of the players is a VIP, the VIP will get a 50% chance of getting the AWP, and the other two players will each have 25% chance of getting the AWP.
  - If you set this to 0, there will be no preference for VIPs.

**Comment by GL1TCH1337** [comment]
If you make NumberOfExtraVipChancesForPreferredWeapon like 99 or something. It will add 1 vip to list 99 times and if there are 5 VIP on the server the list will be 99x5. You can put small numbers but there will be very small chance to a non vip player to get preffered weapon. In my opinion a simple check like this can improve the plugin little bit but you're right.

**Comment by yonilerner** [comment]
Maybe we can keep just `NumberOfExtraVipChancesForPreferredWeapon` but make it so `-1` is a special value that means "VIP only"?

**Comment by GL1TCH1337** [comment]
It is also a good idea instead of adding new config. I will try to implement it. You can modify it afterwards if anything looks bad etc.

**Comment by yonilerner** [comment]
Thank you very much for the contribution!

- Added to docs here: https://github.com/yonilerner/cs2-retakes-allocator/commit/6bf1dcf111813e7d393f76bea291a000d5e1ee14
- New release here: https://github.com/yonilerner/cs2-retakes-allocator/releases/tag/v2.3.4

**Pull request merged**
