### PR TITLE
Make guns work just like gun

### PR DESCRIPTION
**Pull request by yonilerner**
Closes https://github.com/yonilerner/cs2-retakes-allocator/issues/32

### CODE REVIEW

**Comment by B3none** [comment]
I actually think keeping it as `!gun` makes sense, people already have an expectation for what will happen with `!guns` so I think rather than making it an alias we should implement a menu system.

**Comment by yonilerner** [comment]
what if i make `!guns` say "Eventually this will be a weapon menu. For now, please use !gun"

**Comment by B3none** [comment]
That works, definitely keep the handler logic separate for when we allow usage of the commands without a prefix

**Comment by B3none** [comment]
LGTM

**Review by B3none — APPROVED** [review]

**Pull request merged**
