### PR TITLE
Crash On RemovePlayerItem

### PR DESCRIPTION
**Pull request by oqyh**
sorry for delay saw you busy try to fix it RemovePlayerItem cause the crash any gun

Untitled1

Untitled2

- [ x ] https://github.com/yonilerner/cs2-retakes-allocator/issues/106 (Fixed)
- [ x  ]  Finding Sing For Windows  https://github.com/yonilerner/cs2-retakes-allocator/blob/880cf67968b598e15e274d8e45b0c923568c8918/RetakesAllocator/RetakesAllocator.cs#L557 (maybe today)

test on my server lunix works 

and my clients
Untitled

### CODE REVIEW

**Comment by yonilerner** [comment]
@oqyh thank you! seems like this PR needs to be updated to resolve conflicts from your previous PR, but i can approve it after

**Comment by oqyh** [comment]
hello @yonilerner sorry for delay i was busy

using one signature will crash windows servers error locate on PlayerGiveNamedItem

https://streamable.com/fwmqek

**Comment by oqyh** [comment]
i found signature  for windows ill test give you feedback

image

**Comment by oqyh** [comment]
perect works on lunix and windows ill PR

https://streamable.com/2mro8t

**Review by oqyh — COMMENTED** [review]
made auto create file signture called "RetakesAllocator.json" if not found in gamedata

fix sign windows and tested and lunix

**Pull request closed without merging**
